from __future__ import annotations

from typing import Any, Dict, Iterable, List, Sequence, Tuple

try:
    from scripts.revised_core_curriculum_modules import _build_generated_bundle, auto_blueprint, tw
except ModuleNotFoundError:
    from revised_core_curriculum_modules import _build_generated_bundle, auto_blueprint, tw


TermTuple = Tuple[str, str, str]
ControlTuple = Tuple[str, str, str]
ReadoutTuple = Tuple[str, str]


def _terms(items: Sequence[TermTuple]) -> List[Dict[str, str]]:
    return [tw(term, meaning, why) for term, meaning, why in items]


def _bp(
    *,
    slug: str,
    title: str,
    focus: str,
    terms: Sequence[TermTuple],
    core: Sequence[str],
    equation: str,
    meaning: str,
    units: Sequence[str],
    conditions: str,
    summary: str,
    why_prompt: str,
    why_answer: str,
    compare_prompt: str,
    compare_answer: str,
    correct_statement: str,
    distractors: Sequence[str],
    sim_concept: str,
    task_one: str,
    task_two: str,
    controls: Sequence[ControlTuple],
    readouts: Sequence[ReadoutTuple],
    trap: str,
    mapping: Sequence[str],
) -> Dict[str, Any]:
    return auto_blueprint(
        slug=slug,
        title=title,
        focus=focus,
        terms=_terms(terms),
        core_concepts=list(core),
        equation=equation,
        meaning=meaning,
        units=list(units),
        conditions=conditions,
        summary=summary,
        why_prompt=why_prompt,
        why_answer=why_answer,
        compare_prompt=compare_prompt,
        compare_answer=compare_answer,
        apply_prompt=f"Which statement best matches {title.lower()}?",
        apply_choices=[correct_statement, *list(distractors)[:3]],
        apply_answer_index=0,
        sim_concept=sim_concept,
        sim_focus_prompt=f"Use the lesson explorer to keep {focus} visible.",
        sim_description=f"Use the analogy board for {title.lower()} and compare the main quantities together.",
        sim_baseline=f"Start with the default {title.lower()} setup and read the first comparison carefully.",
        sim_tasks=[task_one, task_two],
        sim_takeaway=summary,
        sim_controls=list(controls),
        sim_readouts=list(readouts),
        reflection_prompt=why_prompt,
        trap=trap,
        analogy_check=compare_prompt,
        analogy_mapping=list(mapping),
        visual_concept=sim_concept,
    )


A6_CONTENT_VERSION = "20260323_a6_forge_chamber_count_v2"
A6_MODULE_TITLE = "Thermal Physics and Gases"
A6_MODULE_DESCRIPTION = "Heating pays level costs and morph fees, while gas pressure emerges from wall-hit load and chamber balance, so thermal energy and gas laws stay inside one forge-chamber world."
A6_MASTERY_OUTCOMES = [
    "Explain temperature and internal energy with particle-motion language.",
    "Use specific heat capacity and latent heat as different thermal-bookkeeping rules.",
    "Use gas-law equations and state graphs to connect pressure, volume, temperature, and amount of gas.",
    "Link gas behaviour to kinetic-theory ideas instead of treating the equations as detached rules.",
]

_A6_BLUEPRINTS = [
    _bp(
        slug="internal_energy_temperature",
        title="Internal Energy and Temperature",
        focus="temperature tracks average particle dash while internal energy tracks the whole chamber store",
        terms=[
            ("Temperature", "Temperature tracks the average kinetic energy of the particles.", "It is an average idea, not the whole energy budget."),
            ("Internal energy", "Internal energy is the total microscopic energy of the particles in the system.", "It keeps whole-system energy separate from temperature."),
            ("Average kinetic energy", "Average kinetic energy is the typical motion energy per particle.", "It links particle motion to temperature."),
            ("Thermal equilibrium", "Thermal equilibrium means no net thermal energy transfer between systems in contact.", "It explains why temperatures settle together."),
        ],
        core=[
            "Temperature is an average-per-particle idea.",
            "Internal energy is a whole-system total.",
            "Two systems can share a temperature without sharing the same internal energy.",
            "Thermal equilibrium is about balanced transfer, not motion stopping.",
        ],
        equation="temperature proportional to average kinetic energy",
        meaning="Hotter systems have larger average particle dash, not necessarily the largest total energy.",
        units=["K"],
        conditions="Use as the conceptual bridge before heat-capacity and gas-law calculations.",
        summary="Temperature and internal energy must stay separate because one tracks average dash and the other tracks the whole chamber store.",
        why_prompt="Why can two systems have the same temperature but different internal energies?",
        why_answer="Because temperature tracks average particle kinetic energy, while internal energy depends on the whole number of particles and their full energy store.",
        compare_prompt="How is internal energy different from temperature?",
        compare_answer="Temperature is an average-per-particle measure, while internal energy is the total microscopic energy of the whole system.",
        correct_statement="A large warm chamber can hold more internal energy than a small hotter sample because total energy and average energy are different stories.",
        distractors=[
            "If two systems share a temperature, they must have the same total internal energy.",
            "Temperature is the same thing as the total energy stored in the sample.",
            "Thermal equilibrium means particles stop moving completely.",
        ],
        sim_concept="thermal_store_balance",
        task_one="Increase particle count while keeping average dash fixed and compare the total store.",
        task_two="Raise the average dash while keeping particle count fixed and compare the temperature reading.",
        controls=[
            ("particle_count", "Particle count", "It changes the whole-system energy without automatically changing the average dash."),
            ("dash_level", "Dash level", "It controls the average particle motion linked to temperature."),
        ],
        readouts=[
            ("temperature", "Shows the average particle dash level."),
            ("internal_store", "Shows the whole chamber's microscopic energy total."),
        ],
        trap="Do not collapse temperature and internal energy into the same quantity.",
        mapping=[
            "Warmth level = temperature",
            "Whole forge budget = internal energy",
            "Dash level = average kinetic energy",
            "Balanced chambers = thermal equilibrium",
        ],
    ),
    _bp(
        slug="specific_heat_capacity",
        title="Specific Heat Capacity",
        focus="the level cost sets how much energy is needed per kilogram per degree, so equal heating can still give different temperature rises",
        terms=[
            ("Specific heat capacity", "Specific heat capacity is the energy needed to raise the temperature of one kilogram of a substance by one kelvin.", "It explains why equal heating does not produce equal temperature rises."),
            ("Mass", "Mass is the amount of matter in the sample being heated.", "It changes the total energy needed for a given rise."),
            ("Temperature change", "Temperature change is the difference between final and initial temperature.", "It keeps the rise explicit in thermal calculations."),
            ("Joule", "A joule is the unit of energy transferred.", "It is the bookkeeping unit for heating."),
        ],
        core=[
            "Specific heat capacity is an energy-per-kilogram-per-degree cost.",
            "Larger mass needs more energy for the same temperature rise.",
            "Larger specific heat capacity also needs more energy for the same temperature rise.",
            "The equation is a bookkeeping summary, not a replacement for the heating story.",
        ],
        equation="Q = m c delta T",
        meaning="Thermal energy transfer depends on mass, specific heat capacity, and temperature change.",
        units=["J", "kg", "J kg^-1 K^-1", "K"],
        conditions="Use when heating changes temperature without a state change.",
        summary="Specific heat capacity sets the level cost of heating, so mass, material, and temperature change must all be kept together.",
        why_prompt="Why does the same heater raise different materials by different temperature amounts?",
        why_answer="Because different materials have different specific heat capacities, so the same energy transfer can produce different temperature rises.",
        compare_prompt="How is mass different from specific heat capacity in Q = m c delta T?",
        compare_answer="Mass tells how much material is being heated, while specific heat capacity tells the heating cost per kilogram per degree.",
        correct_statement="A larger c means more energy is needed for the same mass and temperature rise.",
        distractors=[
            "A larger c means the sample automatically starts hotter.",
            "Mass and specific heat capacity play the same role in the equation.",
            "Specific heat capacity only matters during melting and boiling.",
        ],
        sim_concept="heat_capacity_cost",
        task_one="Keep the energy fixed and compare the temperature rise when c changes.",
        task_two="Keep c fixed and compare the energy needed when mass doubles.",
        controls=[
            ("mass", "Mass", "It changes the total energy needed for the same rise."),
            ("heat_capacity", "Level cost", "It changes how much energy each kilogram needs per degree."),
        ],
        readouts=[
            ("energy_input", "Shows the thermal energy transferred into the chamber."),
            ("delta_t", "Shows the resulting temperature change."),
        ],
        trap="Do not treat specific heat capacity as a starting-temperature label.",
        mapping=[
            "Level cost = specific heat capacity",
            "Forge load = mass",
            "Warmth rise = temperature change",
            "Input tokens = thermal energy transferred",
        ],
    ),
    _bp(
        slug="latent_heat",
        title="Latent Heat and Change of State",
        focus="morph fees use energy to rearrange particle links without forcing an immediate temperature rise",
        terms=[
            ("Latent heat", "Latent heat is energy transferred during a change of state without a temperature change.", "It protects the idea that energy can go into rearrangement instead of temperature rise."),
            ("Melting", "Melting is the change of state from solid to liquid.", "It is one place where latent heat is paid."),
            ("Boiling", "Boiling is the change of state from liquid to gas throughout the liquid.", "It uses latent heat to separate particles further."),
            ("State change", "A state change is a change between solid, liquid, and gas.", "It keeps temperature-change stories separate from rearrangement stories."),
        ],
        core=[
            "Latent heat is paid during state change without changing temperature.",
            "The energy goes into changing particle arrangement and link energy.",
            "Melting and boiling use different latent-heat values.",
            "A flat section on a heating curve can still involve ongoing energy transfer.",
        ],
        equation="Q = mL",
        meaning="The latent-heat energy depends on mass and the latent-heat value for that state change.",
        units=["J", "kg", "J kg^-1"],
        conditions="Use during a change of state when temperature stays constant.",
        summary="Latent heat is the morph fee paid to change state, so energy transfer can continue while temperature stays flat.",
        why_prompt="Why can a heater keep transferring energy while the temperature stays constant during melting or boiling?",
        why_answer="Because the energy is being used as latent heat to change the particle arrangement rather than to raise the temperature.",
        compare_prompt="How is latent heat different from specific heat capacity heating?",
        compare_answer="Latent heat changes the state without changing temperature, while specific heat capacity heating changes temperature within one state.",
        correct_statement="A flat section on a heating curve can still mean energy is entering to change the state.",
        distractors=[
            "If temperature stays constant, no energy can be entering the sample.",
            "Melting and boiling use the same latent-heat value in every material.",
            "Latent heat is just another name for temperature.",
        ],
        sim_concept="state_change_fee",
        task_one="Switch from a temperature-rise segment to a state-change segment and compare the readouts.",
        task_two="Increase the mass and compare the size of the latent-heat payment.",
        controls=[
            ("mass", "Mass", "It changes the total latent-heat payment required."),
            ("state_mode", "State mode", "It switches between within-state heating and state change."),
        ],
        readouts=[
            ("temperature", "Shows whether the temperature is rising or staying flat."),
            ("morph_fee", "Shows energy spent on changing state."),
        ],
        trap="Do not conclude that constant temperature means zero energy transfer.",
        mapping=[
            "Morph fee = latent heat",
            "Solid-liquid-gas gate = state change",
            "Flat meter = constant temperature",
            "Rearranged links = changed particle structure",
        ],
    ),
    _bp(
        slug="ideal_gas_law",
        title="Ideal Gas Law and State Variables",
        focus="wall-hit load, room size, dash count, and warmth must be balanced together in one chamber relation",
        terms=[
            ("Pressure", "Gas pressure comes from particle collisions with the container walls.", "It is a wall-hit load, not a stored substance."),
            ("Volume", "Volume is the space available to the gas.", "Changing the room size changes how often particles hit the walls."),
            ("Mole", "A mole is the amount of substance measured in terms of a fixed number of particles.", "It links particle count to gas-law calculations."),
            ("Ideal gas", "An ideal gas is a model where particles have negligible volume and no intermolecular forces except during collisions.", "It gives a clean starting point for gas-law reasoning."),
        ],
        core=[
            "Pressure, volume, temperature, and amount of gas belong in one state story.",
            "The ideal-gas law is a chamber-balance relation.",
            "Changing one state variable often forces another to adjust.",
            "The ideal-gas model is a simplified but useful starting point.",
        ],
        equation="pV = nRT",
        meaning="Pressure times volume matches amount of gas times the gas constant times temperature.",
        units=["Pa", "m^3", "mol", "K"],
        conditions="Use for ideal-gas state calculations with consistent SI units.",
        summary="The ideal-gas law keeps wall-hit load, room size, amount of gas, and warmth in one balanced chamber relation.",
        why_prompt="Why is it dangerous to change one gas variable mentally without checking the others in pV = nRT?",
        why_answer="Because the state variables are linked, so changing one quantity usually forces at least one other quantity to change as well.",
        compare_prompt="How is volume different from amount of gas in pV = nRT?",
        compare_answer="Volume is the space available to the gas, while amount of gas tells how many particles or moles are in the chamber.",
        correct_statement="At fixed n and T, making the chamber smaller raises the pressure.",
        distractors=[
            "At fixed n and T, pressure stays the same when volume halves.",
            "The gas constant changes from one chamber to another.",
            "Pressure depends only on temperature and ignores volume entirely.",
        ],
        sim_concept="gas_state_balance",
        task_one="Keep the amount of gas fixed and compress the chamber to compare the new pressure.",
        task_two="Keep the chamber size fixed and raise the warmth level to compare the wall-hit load.",
        controls=[
            ("pressure", "Wall-hit load", "It shows the gas pressure state."),
            ("volume", "Room size", "It sets how much space the particles have."),
        ],
        readouts=[
            ("state_equation", "Shows the current pV and nRT balance."),
            ("mole_count", "Shows the amount of gas in the chamber."),
        ],
        trap="Do not treat the ideal-gas law as four separate facts instead of one linked state relation.",
        mapping=[
            "Wall-hit load = pressure",
            "Room size = volume",
            "Dash count = amount of gas",
            "Warmth level = temperature",
        ],
    ),
    _bp(
        slug="gas_law_graphs",
        title="Gas Laws and State Graphs",
        focus="state graphs only become readable after the fixed variable is named and the responding pair is tracked together",
        terms=[
            ("Isothermal", "An isothermal change happens at constant temperature.", "It tells which variable was held fixed."),
            ("Isobaric", "An isobaric change happens at constant pressure.", "It labels a process where pressure is fixed."),
            ("Isochoric", "An isochoric change happens at constant volume.", "It labels a process where the chamber size stays fixed."),
            ("State graph", "A state graph shows how gas variables change together during a process.", "It turns equations into process stories."),
        ],
        core=[
            "A gas-law graph only makes sense if the fixed variable is stated.",
            "Different gas-law processes correspond to different graph shapes and proportionalities.",
            "Graphs are process stories, not just picture versions of equations.",
            "The same state variables can be paired in more than one meaningful way.",
        ],
        equation="pV/T = constant for fixed amount of gas",
        meaning="For a fixed amount of gas, pressure, volume, and temperature stay linked through one combined state rule.",
        units=["Pa", "m^3", "K"],
        conditions="Use when the amount of gas stays fixed and the state changes between equilibrium points.",
        summary="Gas-law graphs are easier to trust when the fixed quantity is stated and the responding variables are read as one process story.",
        why_prompt="Why must you name the fixed variable before interpreting a gas-law graph?",
        why_answer="Because the graph shape and meaning depend on which variable stayed constant while the others changed.",
        compare_prompt="How is an isothermal process different from an isobaric process?",
        compare_answer="An isothermal process keeps temperature constant, while an isobaric process keeps pressure constant.",
        correct_statement="A graph is only meaningful if you know which variable was held fixed during the change.",
        distractors=[
            "All gas-law graphs mean the same thing because they use the same three variables.",
            "A straight line on any gas graph proves pressure is constant.",
            "Graphs remove the need to think about the process conditions.",
        ],
        sim_concept="gas_process_graphs",
        task_one="Compare how the graph changes when temperature is fixed instead of pressure.",
        task_two="Track one process on the graph and explain what stays constant during the motion.",
        controls=[
            ("process_type", "Process type", "It selects which variable stays constant."),
            ("graph_mode", "Graph mode", "It chooses which state-variable pair is displayed."),
        ],
        readouts=[
            ("fixed_variable", "Shows which gas variable is being held constant."),
            ("graph_shape", "Shows the current process curve or line."),
        ],
        trap="Do not read a gas graph without first naming the fixed variable.",
        mapping=[
            "Locked dial = fixed variable",
            "State graph = process map",
            "Chamber path = sequence of gas states",
            "Process name = isothermal, isobaric, or isochoric label",
        ],
    ),
    _bp(
        slug="kinetic_theory_bridge",
        title="Kinetic Theory of Gases",
        focus="microscopic dashers and wall collisions explain the macroscopic gas laws instead of replacing them",
        terms=[
            ("Kinetic theory", "Kinetic theory explains gas behaviour using moving particles that collide with each other and the container walls.", "It links microscopic motion to macroscopic gas rules."),
            ("Mean square speed", "Mean square speed is the average of the squared particle speeds.", "It appears in the microscopic pressure relation."),
            ("Random motion", "Random motion means particles move in continually changing directions between collisions.", "It explains why pressure is a statistical wall-collision effect."),
            ("Collision", "A collision is a brief interaction where particles bounce from each other or a wall.", "Gas pressure comes from many wall collisions."),
        ],
        core=[
            "Gas pressure comes from particle-wall collisions.",
            "Higher temperature means higher average kinetic energy and faster particle motion.",
            "Kinetic theory explains why gas-law variables are linked.",
            "Microscopic models and macroscopic laws should support each other.",
        ],
        equation="pV = (1/3) N m <c^2>",
        meaning="The pressure-volume story can be written in terms of particle number, mass, and mean square speed.",
        units=["Pa m^3"],
        conditions="Use as the microscopic bridge from particle motion to gas pressure.",
        summary="Kinetic theory turns gas laws into a wall-collision story by linking pressure to the random dashers inside the chamber.",
        why_prompt="Why does heating a gas raise the pressure of a fixed-volume chamber in kinetic-theory language?",
        why_answer="Because the particles move faster on average and hit the walls harder and more often, so the wall-hit load increases.",
        compare_prompt="How is kinetic theory different from the ideal gas law?",
        compare_answer="The ideal gas law links the macroscopic state variables, while kinetic theory explains that link using particle motion and collisions.",
        correct_statement="Pressure rises at fixed volume because faster particles produce a larger wall-hit load.",
        distractors=[
            "Heating a gas raises pressure because the particles get bigger.",
            "Pressure is stored inside the gas and released only when the chamber opens.",
            "Kinetic theory replaces the gas laws instead of explaining them.",
        ],
        sim_concept="kinetic_theory_bridge",
        task_one="Raise the dash speed and compare the pressure increase at fixed volume.",
        task_two="Lower the particle count and compare the wall-hit load at the same temperature.",
        controls=[
            ("mean_speed", "Dash speed", "It changes the average particle motion."),
            ("particle_count", "Particle count", "It changes how many dashers can hit the walls."),
        ],
        readouts=[
            ("collision_rate", "Shows how often particles hit the walls."),
            ("pressure", "Shows the resulting macroscopic wall-hit load."),
        ],
        trap="Do not treat particle size change as the reason pressure rises when a gas is heated.",
        mapping=[
            "Dashers = gas particles",
            "Wall-hit load = pressure",
            "Collision stream = microscopic cause",
            "Macroscopic dial = gas-law reading",
        ],
    ),
]

A6_MODULE_DOC, A6_LESSONS, A6_SIM_LABS = _build_generated_bundle(
    module_id="A6",
    module_title=A6_MODULE_TITLE,
    content_version=A6_CONTENT_VERSION,
    sequence=25,
    level="Module A6",
    estimated_minutes=90,
    model_name="Forge-Chamber Count Model of Thermal Physics",
    module_description=A6_MODULE_DESCRIPTION,
    mastery_outcomes=A6_MASTERY_OUTCOMES,
    lessons=_A6_BLUEPRINTS,
)


A7_CONTENT_VERSION = "20260323_a7_charge_terrace_switchyard_v2"
A7_MODULE_TITLE = "DC Circuits and Capacitors"
A7_MODULE_DESCRIPTION = "Charges ride boosted loops across node terraces, resistive ramps set the route story, and split-deck stores fill and empty through timed paths."
A7_MASTERY_OUTCOMES = [
    "Explain emf, terminal potential difference, and internal resistance inside one circuit-height story.",
    "Use Kirchhoff rules and potential dividers in multi-component DC networks.",
    "Explain capacitance as charge stored per volt across a separated gap.",
    "Interpret RC charging and discharging, capacitor energy, and dielectric effects conceptually and quantitatively.",
]

_A7_BLUEPRINTS = [
    _bp(
        slug="emf_internal_resistance",
        title="EMF, Terminal PD, and Internal Resistance",
        focus="the lift tower gives a full boost, but internal ramp losses reduce the terminal terrace drop seen by the external circuit",
        terms=[
            ("EMF", "EMF is the energy supplied per unit charge by the source.", "It is the full lift given inside the source before internal losses are counted."),
            ("Terminal potential difference", "Terminal potential difference is the potential difference across the source terminals while the circuit is operating.", "It is the external terrace drop actually available to the rest of the circuit."),
            ("Internal resistance", "Internal resistance is resistance inside the source itself.", "It explains why terminal voltage can be smaller than emf."),
            ("Loaded source", "A loaded source is a source delivering current to a circuit.", "It is the case where internal resistance matters visibly."),
        ],
        core=[
            "EMF is the full source lift per charge.",
            "Terminal PD is the external drop actually delivered to the circuit.",
            "Internal resistance causes some of the source lift to be lost inside the source.",
            "The current depends on the whole loop, not on the source alone.",
        ],
        equation="V_terminal = emf - I r",
        meaning="The terminal potential difference equals the source emf minus the internal drop inside the source.",
        units=["V", "A", "ohm"],
        conditions="Use for a loaded source with internal resistance.",
        summary="A real source gives a full emf lift, but internal resistance steals some of that height before the charge reaches the external circuit.",
        why_prompt="Why can the terminal potential difference be smaller than the emf when current is flowing?",
        why_answer="Because some of the emf is lost across the source's internal resistance when current flows.",
        compare_prompt="How is emf different from terminal potential difference?",
        compare_answer="EMF is the full energy supplied per unit charge, while terminal potential difference is the smaller external voltage after internal losses.",
        correct_statement="As current increases, the internal voltage drop can reduce the terminal potential difference below the emf.",
        distractors=[
            "Terminal potential difference must always equal emf no matter what current flows.",
            "Internal resistance belongs to the external resistor, not to the source.",
            "A battery stores current and sends the same current into every circuit.",
        ],
        sim_concept="source_internal_drop",
        task_one="Increase the external current demand and compare the terminal voltage drop.",
        task_two="Reduce the internal resistance and compare how much emf reaches the external circuit.",
        controls=[
            ("load_current", "Load current", "It changes the size of the internal voltage drop."),
            ("internal_resistance", "Internal ramp", "It sets how much emf is lost inside the source."),
        ],
        readouts=[
            ("emf", "Shows the full lift supplied by the source."),
            ("terminal_pd", "Shows the external voltage available to the circuit."),
        ],
        trap="Do not collapse emf and terminal potential difference into the same quantity.",
        mapping=[
            "Lift tower = emf source",
            "Internal ramp = internal resistance",
            "Outer terrace drop = terminal potential difference",
            "Carrier flow = current",
        ],
    ),
    _bp(
        slug="kirchhoff_node_platforms",
        title="Kirchhoff Laws and Node Platforms",
        focus="node platforms keep ideal-wire points at one terrace height while junction counts and loop heights must balance across the whole mesh",
        terms=[
            ("Node", "A node is a set of ideal-wire points that share the same potential.", "Node heights make complex-circuit reasoning manageable."),
            ("Kirchhoff current law", "Kirchhoff current law says total current entering a junction equals total current leaving.", "It is charge conservation written in junction language."),
            ("Kirchhoff voltage law", "Kirchhoff voltage law says the algebraic sum of potential changes around a closed loop is zero.", "It is energy conservation written in loop language."),
            ("Loop audit", "A loop audit is a systematic check of rises and drops around a closed path.", "It prevents random sign errors in complex circuits."),
        ],
        core=[
            "Ideal-wire points on the same node share the same potential.",
            "Current splits and recombines at junctions according to charge conservation.",
            "Potential rises and drops must balance around a full closed loop.",
            "Complex-circuit analysis becomes easier when node heights are named first.",
        ],
        equation="sum I_in = sum I_out; sum delta V = 0",
        meaning="Junction currents balance and full-loop potential changes also balance.",
        units=["A", "V"],
        conditions="Use in steady-state circuit analysis with a complete loop and consistent sign choices.",
        summary="Kirchhoff analysis is a node-height and junction-count story, not a list of unrelated circuit tricks.",
        why_prompt="Why can two different branches in one circuit still share the same potential difference?",
        why_answer="Because they connect between the same two node platforms, so the terrace drop between their ends is the same even if the currents differ.",
        compare_prompt="How is the junction count rule different from the loop height rule?",
        compare_answer="The junction count rule balances current at a node, while the loop height rule balances rises and drops around a full loop.",
        correct_statement="Name the node heights and then balance junction currents and loop drops systematically.",
        distractors=[
            "Treat every wire point as a different potential even when ideal wire connects them directly.",
            "Assume all currents in parallel branches must be equal because the battery is the same.",
            "Use loop equations only after ignoring the sign of every voltage change.",
        ],
        sim_concept="node_loop_audit",
        task_one="Change one branch resistance and compare the branch currents while watching the shared terrace drop stay fixed.",
        task_two="Walk a full loop and confirm that the rise from the source balances the drops across the components.",
        controls=[
            ("branch_resistance", "Branch drag", "It changes the current in one branch without changing the shared node-to-node voltage."),
            ("source_voltage", "Lift height", "It sets the total loop rise that the drops must match."),
        ],
        readouts=[
            ("node_potentials", "Shows which points share one terrace height."),
            ("junction_balance", "Shows whether current entering and leaving the node balances."),
        ],
        trap="Do not treat every point in a complex circuit as if it must have a different potential.",
        mapping=[
            "Node platform = common potential node",
            "Junction count rule = Kirchhoff current law",
            "Loop height rule = Kirchhoff voltage law",
            "Mesh audit = complex-circuit analysis",
        ],
    ),
    _bp(
        slug="potential_dividers",
        title="Potential Dividers",
        focus="a divider stair shares one source height into selected terrace drops across series sections",
        terms=[
            ("Potential divider", "A potential divider is a series arrangement used to take a chosen fraction of the input voltage.", "It turns one source height into a controlled output height."),
            ("Output voltage", "Output voltage is the potential difference taken across the selected section of the divider.", "It is the useful terrace drop read from the network."),
            ("Series resistor", "A series resistor is a resistor placed in line so the same current passes through it.", "Divider logic depends on one shared current in the chain."),
            ("Variable resistor", "A variable resistor can change its resistance value during operation.", "It makes adjustable potential dividers possible."),
        ],
        core=[
            "A potential divider works because the same current passes through the whole series chain.",
            "The output voltage is one chosen fraction of the full input voltage.",
            "Changing one section resistance changes the fraction of the source drop taken there.",
            "Divider reasoning is a height-sharing story, not a current-sharing story.",
        ],
        equation="V_out / V_in = R_section / R_total",
        meaning="The output voltage fraction matches the resistance fraction for one series section.",
        units=["V", "ohm"],
        conditions="Use for an unloaded or appropriately treated series potential divider.",
        summary="A potential divider shares one source height into controlled terrace drops across a series stair.",
        why_prompt="Why does increasing one divider section resistance increase the output voltage across that section?",
        why_answer="Because that section then takes a larger fraction of the total series resistance, so it gets a larger fraction of the source voltage.",
        compare_prompt="How is a potential divider different from a pair of parallel branches?",
        compare_answer="A potential divider is a series height-sharing arrangement, while parallel branches share the full same voltage across each branch.",
        correct_statement="The chosen output section gets the same fraction of the input voltage as its resistance fraction of the total series resistance.",
        distractors=[
            "A larger divider resistance always means a smaller voltage across that section no matter the layout.",
            "Potential dividers work by forcing equal current into every branch of a parallel network.",
            "The output voltage is unrelated to how the total resistance is split in the series chain.",
        ],
        sim_concept="divider_stair",
        task_one="Increase the selected section resistance and compare the new output fraction.",
        task_two="Move the output taps to a different section and compare which terrace drop is being measured.",
        controls=[
            ("upper_resistance", "Upper stair height", "It helps decide how the full source drop is shared."),
            ("lower_resistance", "Lower stair height", "It sets the selected output fraction."),
        ],
        readouts=[
            ("input_voltage", "Shows the full source terrace drop."),
            ("output_voltage", "Shows the chosen divider output."),
        ],
        trap="Do not treat a potential divider like a parallel-branch current-sharing problem.",
        mapping=[
            "Divider stair = series potential divider",
            "Chosen step drop = output voltage",
            "Full stair height = input voltage",
            "Adjustable step = variable resistor",
        ],
    ),
    _bp(
        slug="capacitance_basics",
        title="Capacitance and Charge Storage",
        focus="a split-deck store holds separated charge across a gap, and its hold capacity tells how much charge fits per volt of terrace drop",
        terms=[
            ("Capacitance", "Capacitance is the charge stored per unit potential difference.", "It tells how much charge a capacitor can hold for each volt."),
            ("Capacitor", "A capacitor is a component made of two conductors separated by an insulator.", "It stores separated charge and energy in the electric field between the plates."),
            ("Plate charge", "Plate charge is the equal and opposite charge gathered on the capacitor plates.", "It is the visible stored-charge story of the component."),
            ("Potential difference", "Potential difference is the voltage across the capacitor plates.", "Capacitance connects the stored charge to this terrace drop."),
        ],
        core=[
            "A capacitor stores equal and opposite charge on facing conductors.",
            "Capacitance tells how much charge is stored per volt.",
            "The gap stops charge crossing directly while allowing an electric field to form.",
            "Stored energy lives in the field between the plates.",
        ],
        equation="C = Q / V",
        meaning="Capacitance equals stored charge divided by the potential difference across the capacitor.",
        units=["F", "C", "V"],
        conditions="Use for capacitor charge-voltage relations in a fixed geometry.",
        summary="A capacitor is a split-deck store whose hold capacity says how much separated charge fits per volt.",
        why_prompt="Why does a capacitor need two facing conductors rather than one isolated plate?",
        why_answer="Because the capacitor stores equal and opposite charge across a gap, creating the field and potential difference between the two facing conductors.",
        compare_prompt="How is capacitance different from the actual charge stored on a capacitor?",
        compare_answer="Capacitance is the fixed storage-per-volt property of the capacitor, while the stored charge is the actual amount on the plates at one moment.",
        correct_statement="A larger capacitance means more charge can be stored for the same potential difference.",
        distractors=[
            "A larger capacitance means the capacitor automatically has more voltage even when uncharged.",
            "Capacitance is the same thing as the stored charge.",
            "A capacitor stores charge because charge crosses the insulator gap directly.",
        ],
        sim_concept="split_deck_store",
        task_one="Increase the capacitance and compare how much charge is stored at the same voltage.",
        task_two="Keep the capacitance fixed and raise the source voltage to compare the stored charge.",
        controls=[
            ("capacitance", "Hold capacity", "It changes how much charge fits per volt."),
            ("source_voltage", "Charging height", "It sets the terrace drop across the plates."),
        ],
        readouts=[
            ("plate_charge", "Shows the equal and opposite charge on the plates."),
            ("voltage", "Shows the terrace drop across the capacitor gap."),
        ],
        trap="Do not confuse capacitance with the actual charge stored at one moment.",
        mapping=[
            "Split-deck store = capacitor",
            "Hold capacity = capacitance",
            "Plate charge = stored separated charge",
            "Terrace drop = potential difference",
        ],
    ),
    _bp(
        slug="rc_charging_discharging",
        title="RC Charging and Discharging",
        focus="a capacitor fills and empties through a drag path, so the charge and voltage change with a time-pattern instead of an instant jump",
        terms=[
            ("Time constant", "The time constant is the characteristic timescale RC that sets how quickly a capacitor charges or discharges through a resistor.", "It ties resistance and capacitance into one timing rule."),
            ("Charging curve", "A charging curve shows the capacitor voltage rising toward its final value over time.", "It makes the non-instant fill visible."),
            ("Discharging curve", "A discharging curve shows the capacitor voltage falling from its initial value over time.", "It shows that stored charge leaks away through the resistor path."),
            ("Exponential change", "Exponential change is fast at first and then gradually slows.", "RC curves are shaped this way rather than as straight lines."),
        ],
        core=[
            "A resistor slows the rate at which a capacitor charges or discharges.",
            "The time constant RC sets the overall timing scale.",
            "Charging and discharging are exponential, not linear, processes.",
            "The capacitor current falls as the capacitor approaches its new voltage state.",
        ],
        equation="V = V0 e^(-t/RC) for discharge",
        meaning="During discharge, the capacitor voltage falls exponentially with a timescale set by RC.",
        units=["V", "s", "ohm", "F"],
        conditions="Use for simple RC charging or discharging when one resistor and one capacitor set the timescale.",
        summary="RC circuits change with a timed fill-and-empty curve because the resistor path controls how fast the capacitor can adjust.",
        why_prompt="Why does a capacitor not jump to its final voltage instantly when charging through a resistor?",
        why_answer="Because the resistor limits the current, so the capacitor charge and voltage build up gradually over the RC timescale.",
        compare_prompt="How is the time constant different from the final capacitor voltage?",
        compare_answer="The time constant tells how quickly the change happens, while the final voltage tells the level the capacitor is approaching.",
        correct_statement="A larger resistance or capacitance makes the charge and voltage change more slowly.",
        distractors=[
            "The resistor only affects the final voltage and never the timing.",
            "RC curves are straight lines because the same amount changes every second.",
            "A capacitor discharges instantly because stored charge cannot remain in the loop.",
        ],
        sim_concept="rc_charge_path",
        task_one="Double the resistance and compare how long it takes the capacitor to approach the same final voltage.",
        task_two="Switch to discharge mode and compare the shape of the fall to the earlier charging rise.",
        controls=[
            ("resistance", "Drag path", "It slows the charging and discharging current."),
            ("capacitance", "Hold capacity", "It changes how much charge must build for a given voltage."),
        ],
        readouts=[
            ("time_constant", "Shows the RC timescale."),
            ("capacitor_voltage", "Shows the changing capacitor terrace height."),
        ],
        trap="Do not read an RC charging curve as if it were a straight-line constant-rate process.",
        mapping=[
            "Discharge trail = RC path",
            "Hold capacity = capacitance",
            "Drag path = resistance",
            "Fill curve = charging/discharging graph",
        ],
    ),
    _bp(
        slug="capacitor_energy_dielectrics",
        title="Capacitor Energy and Dielectrics",
        focus="the field-filled gap stores energy, and geometry or dielectric changes alter how much charge can be held for each volt",
        terms=[
            ("Stored energy", "Stored energy in a capacitor is the energy held in the electric field between the plates.", "It explains why capacitors can later release useful energy."),
            ("Dielectric", "A dielectric is an insulating material placed between the capacitor plates.", "It can increase the capacitance by changing the field conditions in the gap."),
            ("Plate area", "Plate area is the facing size of the capacitor plates.", "Larger facing area usually increases capacitance."),
            ("Plate separation", "Plate separation is the distance between the capacitor plates.", "Larger separation usually decreases capacitance."),
        ],
        core=[
            "Capacitor energy is stored in the electric field between the plates.",
            "Larger capacitance lets more charge be stored for the same voltage.",
            "Increasing plate area increases capacitance, while increasing separation decreases it.",
            "A dielectric changes how the field-filled gap stores charge and energy.",
        ],
        equation="E = 1/2 C V^2",
        meaning="The stored energy depends on both capacitance and voltage.",
        units=["J", "F", "V"],
        conditions="Use for the electrical energy stored in a capacitor.",
        summary="Capacitor energy lives in the field-filled gap, and dielectric or geometry changes alter how much the split-deck store can hold.",
        why_prompt="Why does increasing plate area usually increase capacitance in a parallel-plate capacitor?",
        why_answer="Because a larger facing area lets more separated charge be stored for the same potential difference across the gap.",
        compare_prompt="How is stored capacitor energy different from capacitance itself?",
        compare_answer="Stored energy is the actual energy held in the field, while capacitance is the storage-per-volt property of the device.",
        correct_statement="A larger plate area usually increases capacitance, while a wider gap usually decreases it.",
        distractors=[
            "Plate area has no effect because only the battery sets the capacitance.",
            "A dielectric lowers capacitance by removing the field from the gap.",
            "Stored energy and capacitance are the same physical quantity.",
        ],
        sim_concept="capacitor_geometry_store",
        task_one="Increase the plate area and compare the new capacitance and stored energy.",
        task_two="Insert a dielectric and compare how the hold capacity changes at the same voltage.",
        controls=[
            ("plate_area", "Facing area", "It changes how much separated charge the plates can support."),
            ("gap", "Plate gap", "It changes the field geometry across the capacitor."),
        ],
        readouts=[
            ("capacitance", "Shows the hold capacity of the capacitor."),
            ("stored_energy", "Shows the energy held in the electric field."),
        ],
        trap="Do not treat the battery as the only thing deciding the capacitor's storage capacity.",
        mapping=[
            "Field-filled gap = stored-energy region",
            "Facing area = plate area",
            "Gap width = plate separation",
            "Gap material = dielectric",
        ],
    ),
]

A7_MODULE_DOC, A7_LESSONS, A7_SIM_LABS = _build_generated_bundle(
    module_id="A7",
    module_title=A7_MODULE_TITLE,
    content_version=A7_CONTENT_VERSION,
    sequence=26,
    level="Module A7",
    estimated_minutes=90,
    model_name="Charge-Terrace Switchyard Model of DC Circuits and Capacitors",
    module_description=A7_MODULE_DESCRIPTION,
    mastery_outcomes=A7_MASTERY_OUTCOMES,
    lessons=_A7_BLUEPRINTS,
)
